# Определение версии Docker Compose и начало описания сервисов
version: '3'

services:
  django:
    # Сборка образа для сервиса django из текущей директории
    build: .
    # Задание имени контейнера для сервиса django
    container_name: django
    # Задание команды, которую нужно запустить при запуске контейнера для сервиса django
    command: gunicorn beer_brain.wsgi -b '0.0.0.0:8000'
    # Открытие порта на хостовой машине и перенаправление на порт в контейнере
    ports:
      - 8000:8000
    env_file:
      - .env.prod
    # Зависимость от другого сервиса
    depends_on:
      - postgres

  postgres:
    # Использование готового образа postgres
    image: postgres
    # Задание переменных окружения для контейнера с postgres
    env_file:
      - .env.prod
      # Задание имени контейнера для сервиса pgdb
    container_name: postgres
    # Связывание тома с директорией в контейнере для сохранения данных postgres
    volumes:
      - pgdbdata:/var/lib/postgresql/data/

volumes:
  pgdbdata: null