# Generated by Django 4.2.5 on 2024-01-13 11:24

from django.db import migrations, models

import beer_brain.users.validators


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="username",
            field=models.CharField(
                error_messages={"unique": "A user with that username already exists."},
                help_text="Required. 3-128 characters. Letters, digits and _ only.",
                max_length=128,
                unique=True,
                validators=[beer_brain.users.validators.UsernameValidator()],
                verbose_name="username",
            ),
        ),
    ]
