# Generated by Django 4.2.5 on 2024-01-19 14:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0002_deposit_event"),
    ]

    operations = [
        migrations.AddField(
            model_name="repayment",
            name="description",
            field=models.CharField(blank=True, max_length=256),
        ),
    ]
