# Generated by Django 4.2.5 on 2024-04-19 11:34

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def forwards_func(apps, schema_editor):
    Deposit = apps.get_model("events", "Deposit")
    Repayment = apps.get_model("events", "Repayment")
    Transaction = apps.get_model("events", "Transaction")
    Movement = apps.get_model("events", "Movement")

    # Создание Transaction для каждого объекта Deposit
    for deposit in Deposit.objects.all():
        transaction = Transaction.objects.create(
            id=uuid.uuid4(),
            event=deposit.event,
            description=deposit.description,
            datetime=deposit.payed_at,
        )
        # Создание Movement для Deposit
        Movement.objects.create(
            id=uuid.uuid4(),
            user=deposit.user,
            transaction=transaction,
            delta=deposit.value,
        )

    # Создание Transaction для каждого объекта Repayment
    for repayment in Repayment.objects.all():
        transaction = Transaction.objects.create(
            id=uuid.uuid4(),
            event=repayment.event,
            description=repayment.description,
            datetime=repayment.payed_at,
        )
        # Создание Movement для Repayment
        Movement.objects.create(
            id=uuid.uuid4(),
            user=repayment.payer,
            transaction=transaction,
            delta=repayment.value,
        )
        Movement.objects.create(
            id=uuid.uuid4(),
            user=repayment.recipient,
            transaction=transaction,
            delta=-repayment.value,
        )


def backwards_func(apps, schema_editor):
    pass


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("events", "0003_repayment_description"),
    ]

    operations = [
        migrations.CreateModel(
            name="Transaction",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("description", models.CharField(blank=True, max_length=256)),
                ("datetime", models.DateTimeField(auto_now_add=True)),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transactions",
                        to="events.event",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Movement",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("delta", models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ("cancel", models.BooleanField(default=False)),
                (
                    "transaction",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="movements",
                        to="events.transaction",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="movements",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.RunPython(forwards_func, backwards_func),
    ]
