# Generated by Django 4.2.5 on 2024-04-19 12:16

from django.db import migrations


def forwards_func(apps, schema_editor):
    pass


def back_func(apps, schema_editor):
    Deposit = apps.get_model("events", "Deposit")
    Repayment = apps.get_model("events", "Repayment")
    Transaction = apps.get_model("events", "Transaction")

    for transaction in Transaction.objects.all():
        value = sum(m.delta for m in transaction.movements.all())

        if value == 0:
            movement_payer = transaction.movements.filter(delta__gt=0).first()
            movement_recipient = transaction.movements.filter(delta__lt=0).first()

            Repayment.objects.create(
                payer=movement_payer.user,  # Плательщик - пользователь из Movement
                recipient=movement_recipient.user,
                event=transaction.event,
                value=movement_payer.delta,  # Используйте абсолютное значение для выплаты
                description=transaction.description,
                payed_at=transaction.datetime,
            )
        else:
            Deposit.objects.create(
                user=transaction.movements.first().user,
                event=transaction.event,
                value=sum(m.delta for m in transaction.movements.all()),
                description=transaction.description,
                payed_at=transaction.datetime,
            )


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0004_transaction_movement"),
    ]

    operations = [
        migrations.RunPython(forwards_func, back_func),
        migrations.RemoveField(
            model_name="repayment",
            name="event",
        ),
        migrations.RemoveField(
            model_name="repayment",
            name="payer",
        ),
        migrations.RemoveField(
            model_name="repayment",
            name="recipient",
        ),
        migrations.DeleteModel(
            name="Deposit",
        ),
        migrations.DeleteModel(
            name="Repayment",
        ),
    ]
