# Generated by Django 4.2.5 on 2024-04-20 14:03

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("events", "0005_remove_repayment_event_remove_repayment_payer_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="movement",
            unique_together={("user", "transaction")},
        ),
    ]
